services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /_health
    autoDeploy: false
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~18.15.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_FILENAME
        value: /.tmp/data.db
 
